export enum Tag {
  GLUTEN_FREE = 'GLUTEN_FREE',
  LACTOSE_FREE = 'LACTOSE_FREE',
  VEGAN = 'VEGAN',
  VEGETARIAN = 'VEGETARIAN',
  NUT_FREE = 'NUT_FREE',
  HALAL = 'HALAL',
  KOSHER = 'KOSHER',
  BIO = 'BIO',
}
